---
# tasks file for app-deployment
- name: Update apt repository
  apt:
    update_cache: yes

- name: install Java-jdk
  apt:
    name: openjdk-17-jdk
    state: latest
  
- name: Install curl
  ansible.builtin.package:
      name: curl
      state: present

- name: Download Docker installation script
  ansible.builtin.shell: "curl -fsSL https://get.docker.com -o /tmp/get-docker.sh"
  args:
    creates: /tmp/get-docker.sh

- name: Run Docker installation script
  ansible.builtin.shell: "sh /tmp/get-docker.sh"
  args:
    creates: /usr/bin/docker

- name: Start and enable Docker service
  ansible.builtin.systemd:
    name: docker
    enabled: yes
    state: started

- name: Add the current user to the docker group
  ansible.builtin.user:
    name: "ubuntu"  # Use the current user running the playbook
    groups: docker
    append: yes
